name: Create Tag And Deploy In PROD_ENV

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  create-tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 2026-04-06过期
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 确保获取所有历史以便正确生成标签
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Git
        run: |
          echo "🏠 Setting global git config informations"
          git config --global user.email "347258143@qq.com"
          git config --global user.name "Junlin-Robin"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Create and Push Tag
        id: create-and-push-tag
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 2026-04-06过期
        run: |
          # 更新日志文件路径
          CHANGE_LOG_FILE_PATH=.change-log
          CHANGE_LOG_FILE_NAME=index.md
          # 移动后，文档路由更新日志路径
          LOG_PATH=docs/change-log
          # 当前日期
          CURRENT_DATE=$(date +%Y-%m-%d)

          # 判断更新日志是否存在
          if [ -f ${CHANGE_LOG_FILE_PATH}/${CHANGE_LOG_FILE_NAME} ]
          then

            echo "-------------------------------------------------------------"

            echo "🚀 存在更新日志，开始提取日志"

            echo "-------------------------------------------------------------"

            # 判断文档路由下更新日志是否已经存在
            if [ -f ${LOG_PATH}/${CURRENT_DATE}.md ]
            then

              echo "🟢 已存在文档路由更新日志，追加内容中..."

              cat ${CHANGE_LOG_FILE_PATH}/${CHANGE_LOG_FILE_NAME} >> ${LOG_PATH}/${CURRENT_DATE}.md

              echo "📓 日志内容已追加到 ${LOG_PATH}/${CURRENT_DATE}.md 文档中"

            else

              echo "🔴 不存在文档路由更新日志，开始创建..."

              touch ${LOG_PATH}/${CURRENT_DATE}.md

              echo "---" >> ${LOG_PATH}/${CURRENT_DATE}.md
              echo "nav:" >> ${LOG_PATH}/${CURRENT_DATE}.md
              echo "  title: 更新日志" >> ${LOG_PATH}/${CURRENT_DATE}.md
              echo "  order: 4" >> ${LOG_PATH}/${CURRENT_DATE}.md
              echo "---" >> ${LOG_PATH}/${CURRENT_DATE}.md
              echo ""


              cat ${CHANGE_LOG_FILE_PATH}/${CHANGE_LOG_FILE_NAME} >> ${LOG_PATH}/${CURRENT_DATE}.md

              echo "📓 已成功创建 ${LOG_PATH}/${CURRENT_DATE}.md 文档，并写入日志"

            fi

          else

            echo "-------------------------------------------------------------"

            echo "❌ 无更新日志，退出"

            echo "-------------------------------------------------------------"

            exit 0

          fi

          TAG_INDEX=1
          NEW_VERSION_TAG=v_${CURRENT_DATE}_${TAG_INDEX}

          while true
          do
            NEW_VERSION_TAG=v_${CURRENT_DATE}_${TAG_INDEX}
            if git tag | grep -q $NEW_VERSION_TAG
            then
              TAG_INDEX=$((TAG_INDEX+1))
              continue
            else
              break
            fi
          done

          

          echo "当前版本为 ${NEW_VERSION_TAG}"

          echo "-------------------------------------------------------------"

          echo "🚀 升级版本类型为：patch，升级后版本号为：$NEW_VERSION_TAG"

          echo "-------------------------------------------------------------"

          echo "TAG_FILE_PATH=${CHANGE_LOG_FILE_PATH}/${CHANGE_LOG_FILE_NAME}" >> $GITHUB_ENV
          echo "NEW_VERSION_TAG=${NEW_VERSION_TAG}" >> $GITHUB_ENV
          echo "TAG_NAME=${NEW_VERSION_TAG}" >> $GITHUB_OUTPUT

          # 推送更新版本号和 tag 到 master 分支
          echo "🚗 推送更新版本号和 tag 到 master 分支..."
          git add .
          git commit -m 'docs: 归档日志文档文件'
          git push --force
          git push origin master

          # 获取最新提交的哈希
          LATEST_COMMIT=$(git rev-parse HEAD)
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV

      - name: Checkout latest master
        run: |
          git checkout master
          git pull origin master      

      - name: Read Release Markdown File
        id: Read-Release-File
        run: |
          echo "📖 读取更新版本日志文件..."
          CONTENT=$(cat '${{env.TAG_FILE_PATH}}')
          CONTENT="${CONTENT//'%'/'%25'}"
          CONTENT="${CONTENT//$'\n'/'%0A'}"
          CONTENT="${CONTENT//$'\r'/'%0D'}"
          echo "::set-output name=CONTENT::$CONTENT"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION_TAG }}
          release_name: Release ${{ env.NEW_VERSION_TAG }}
          body: ${{ steps.Read-Release-File.outputs.CONTENT }}
          draft: false
          prerelease: false
          commitish: ${{ env.LATEST_COMMIT }}

    outputs:
      TAG_NAME: ${{ steps.create-and-push-tag.outputs.TAG_NAME }}

  deploy-in-production:
    needs: [create-tag-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 确保获取所有历史以便正确生成标签
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: checkout tag
        run: |
          echo "当前 Tag 为 ${{ needs.create-tag-release.outputs.TAG_NAME }}"

          git checkout ${{ needs.create-tag-release.outputs.TAG_NAME }}
          
          echo "已切换到 ${{ needs.create-tag-release.outputs.TAG_NAME }} 🟢"

      - name: Install Dependencies
        run: yarn

      - name: Build
        id: build-environment
        run: |
          echo "🔧 开始配置打包环境..."
          ENV=production
          echo "ENV=$ENV" >> $GITHUB_ENV

          OUT_DIR=dist
          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV

          echo "-------------------------------------------------------------"

          echo "当前环境为：生产环境，打包输出目录为：$OUT_DIR 🏭"

          echo "-------------------------------------------------------------"

          echo "📦 开始对 dumi 项目打包..."
          yarn run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # 部署到 gh-pages 分支
          folder: ${{ env.OUT_DIR }} # 部署目录见配置
          target-folder: / # 部署根目录
          clean: true # 先清理之前的部署
          token: ${{ secrets.GITHUB_TOKEN }}
